version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        description: 'ID of the customer. Unique identifier of the customer'
        tests:
        - unique
        - not_null

  - name: stg_products
    columns:
    - name: product_id
      description: 'Id of the product. Unique Identifier of the product'
      tests:
        - not_null
        - unique

  - name: stg_store
    columns:
    - name: store_id
      description: 'Id of the store. Unique Identifier of the store'
      tests:
        - not_null
        - unique
        
  - name: stg_sales
    columns:
      - name: customer_id
        tests:
          - not_null
      - name: sale_date
        tests:
          - not_null