version: 2

sources:
  - name: sources_tables
    tables:
      - name: fact_sales
        columns:
          - name: customer_id
            tests:
            - not_null
      - name: dim_customers
        columns:
          - name: customer_id
            tests:
            - not_null
      - name: dim_stores
      - name: dim_products